"""Fix processed_messages model

Revision ID: 11565c162c66
Revises: 
Create Date: 2025-08-02 20:25:19.448546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11565c162c66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processed_messages', 'message_id',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_processed_messages_message_id'), 'processed_messages', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_messages_message_id'), table_name='processed_messages')
    op.alter_column('processed_messages', 'message_id',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
