"""add_contact_number_asked_to_deals

Revision ID: 75b7a4b42c57
Revises: 9b6deb3a79f4
Create Date: 2025-09-17 22:34:09.150690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b7a4b42c57'
down_revision: Union[str, None] = '9b6deb3a79f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('contact_number_asked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'contact_number_asked')
    # ### end Alembic commands ###
