"""add_course_related_users_table

Revision ID: 9b6deb3a79f4
Revises: 8b2f3a1c9d10
Create Date: 2025-09-14 21:39:04.561704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6deb3a79f4'
down_revision: Union[str, None] = '8b2f3a1c9d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_related_users',
    sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
    sa.Column('instagram_username', sa.String(length=255), nullable=False),
    sa.Column('brideside_vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(6), nullable=False),
    sa.Column('updated_at', sa.DateTime(6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['brideside_vendor_id'], ['brideside_vendors.id'], ondelete='CASCADE')
    )
    op.create_index('ix_course_related_vendors_vendor_id', 'course_related_users', ['brideside_vendor_id'], unique=False)
    op.create_index('ix_course_related_vendors_id', 'course_related_users', ['id'], unique=False)
    op.create_index('ix_course_related_vendors_instagram_username', 'course_related_users', ['instagram_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_related_vendors_instagram_username', table_name='course_related_users')
    op.drop_index('ix_course_related_vendors_id', table_name='course_related_users')
    op.drop_index('ix_course_related_vendors_vendor_id', table_name='course_related_users')
    op.drop_table('course_related_users')
    # ### end Alembic commands ###
